#'
#'  simulate a cluster population distribution from the fittedmodel or given parameters
#'
#'@usage
#'rCluster(params,N_expect,covrs)
#'rMatern(sigma2,alpha,en.filter,plotdim,N,nu=0.5,xcell=1,ycell=1)
#'
#' @param params a vector contains parameters of a cluster population model. it is commonly 
#' a fm object retruned by the \code{\link{fitCluster}} function. 
#' @param covrs a list of im objects which represent the observed environmental variables.
#' @param sigma2 a paramter in the Matern covariance function that controls the flat of the covariance.
#'        the larger the sigma2 is, the longer tail the covariance is.
#' @param alpha a parameter in the Matern covariance function
#' @param en.filter a im object that is a linear conbination of covariables.
#' @param plotdim the maximun value of x and y values of individual location.
#' @param nu a parameter controls the sharp of the Matern covariance function.
#'        if it equals to Inf, the Matern covariance function is corresponding to the 
#'        log-Gauss function.
#' @param xcell,ycell the size of grid used in generate random points.
#' 
#' @details
#' A simulated point pattern was generated by the two step approach: first generate a point density map
#' accroding to the internal cluster process, then a thinning process was carried out accroding to the 
#' linear correlation function between point intensity map and habitat variables. 
#' Note that this function only generate a point pattern. attributes/traits (except species name) of individuals can't be
#' generated for new indviduals without any extra assumption.
#' 
#'@return 
#'  a ppp object
#' 
#'@examples
#'
#'#load data and get one species
#'data(testData)
#'sp1=subset(testData,testData$traits$species=="HYBAPR")
#'
#'#fit a cluster model
#'fittedmodel=fitCluster(sp1,~elev+grad)
#'
#'#generate new simulated population data
#'rCluster(fittedmodel,sp1$N,sp1$habitat)
#' 


rCluster<-function(params,N_expect,covrs){
  #extact parameters
  beta=params[-c(1:4)]
  integer=params[4]
  sigma2=params["sigma2"]
  alpha=params["alpha"]
  nu=params["nu"]
  plotdim=c(covrs[[1]]$xrange[2],covrs[[1]]$yrange[2])
  covri=match(names(beta),names(covrs))
  subcovrs=covrs[covri]
  numCov=length(subcovrs)
  xcell=covrs[[1]]$xstep
  ycell=covrs[[1]]$ystep
  #constract a environmental filter
  if(numCov!=0){
    en.filter=subcovrs[[1]]
    en.filter$v=subcovrs[[1]]$v*beta[1]
    for(i in 2:numCov){
      en.filter$v=en.filter$v+subcovrs[[i]]$v*beta[i]
    }
    en.filter$v=en.filter$v+integer
  }else{
    en.filter=NULL
  }
  
  #generate the point pattern
  X=rMatern(sigma2,alpha,en.filter,plotdim,N_expect,nu,xcell,ycell)
  return(X)
}

#simulate a Matern Cluster point process by the given parameters

rMatern=function(sigma2,alpha,en.filter,plotdim,N,nu=0.5,xcell=1,ycell=1){
  
  xcol=seq(xcell/2,plotdim[1],xcell)
  yrow=seq(ycell/2,plotdim[2],ycell)
  
  if(nu!=Inf){
    Y <- GaussRF(x=xcol, y=yrow, model="matern", grid=TRUE,
                 param=c(mean=0.0, variance=sigma2, nugget=0.0, scale=alpha,nu=nu))
  }else{
    Y <- GaussRF(x=xcol, y=yrow, model="gauss", grid=TRUE,
                 param=c(mean=0.0, variance=sigma2, nugget=0.0, scale=alpha/sqrt(0.5)))
  }
  Yim <- as.im(list(x = xcol, y = yrow, z = Y))

  if(!is.null(en.filter)){
    Lambda=en.filter
    mu=log(N/sum(exp(en.filter$v+0.5*sigma2)*xcell*ycell))
    Lambda$v=exp(mu+en.filter$v+Yim$v)
  }else{
    mu=log(N/sum(exp(0.5*sigma2)*xcell*ycell))
    Lambda=Yim
    Lambda$v=exp(mu+Yim$v)
  }
  
  #simulate inhomogeneous Poisson process with intensity function given by Lambda.
  X=rpoispp(Lambda)
  return(X)
}
