# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

comdistntInner <- function(N, dis, x, exclude_conspecifics, cal_pairs) {
    .Call('sce_comdistntInner', PACKAGE = 'sce', N, dis, x, exclude_conspecifics, cal_pairs)
}

commdistInner <- function(N, dis, x, cal_pairs) {
    .Call('sce_commdistInner', PACKAGE = 'sce', N, dis, x, cal_pairs)
}

phyloBeta_C <- function(N, dis, x, qxy, rmax, exclude_conspecifics = TRUE, indextype = 0L) {
    .Call('sce_phyloBeta_C', PACKAGE = 'sce', N, dis, x, qxy, rmax, exclude_conspecifics, indextype)
}

