# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nearest_neighbors <- function(xy, rmax, nguess) {
    .Call('sce_nearest_neighbors', PACKAGE = 'sce', xy, rmax, nguess)
}

rcpp_hello_world <- function() {
    .Call('sce_rcpp_hello_world', PACKAGE = 'sce')
}

