# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nearest_neighbors <- function(xy, rmax) {
    .Call('sce_nearest_neighbors', PACKAGE = 'sce', xy, rmax)
}

rcpp_hello_world <- function() {
    .Call('sce_rcpp_hello_world', PACKAGE = 'sce')
}

SAR_approximateC <- function(longxy, latxy, scp, long_all, lat_all, area, nrep, max_area) {
    .Call('sce_SAR_approximateC', PACKAGE = 'sce', longxy, latxy, scp, long_all, lat_all, area, nrep, max_area)
}

